/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_UP_TNLInformation_H_
#define	_Ngap_UP_TNLInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_UP_TNLInformation_PR {
	Ngap_UP_TNLInformation_PR_NOTHING,	/* No components present */
	Ngap_UP_TNLInformation_PR_singleTNLInformation,
	Ngap_UP_TNLInformation_PR_multipleTNLInformation,
	Ngap_UP_TNLInformation_PR_choice_Extensions
} Ngap_UP_TNLInformation_PR;

/* Forward declarations */
struct Ngap_SingleTNLInformation;
struct Ngap_MultipleTNLInformation;
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_UP-TNLInformation */
typedef struct Ngap_UP_TNLInformation {
	Ngap_UP_TNLInformation_PR present;
	union Ngap_UP_TNLInformation_u {
		struct Ngap_SingleTNLInformation	*singleTNLInformation;
		struct Ngap_MultipleTNLInformation	*multipleTNLInformation;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_UP_TNLInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_UP_TNLInformation;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_UP_TNLInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_UP_TNLInformation_1[3];
extern asn_per_constraints_t asn_PER_type_Ngap_UP_TNLInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_UP_TNLInformation_H_ */
#include <asn_internal.h>
