/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "asn.1/Container Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_ProtocolIE_Container_H_
#define	_Ngap_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_PDUSessionResourceModifyRequestTransferIEs;
struct Ngap_PDUSessionResourceSetupRequestTransferIEs;
struct Ngap_PDUSessionResourceSetupRequestIEs;
struct Ngap_PDUSessionResourceSetupResponseIEs;
struct Ngap_PDUSessionResourceReleaseCommandIEs;
struct Ngap_PDUSessionResourceReleaseResponseIEs;
struct Ngap_PDUSessionResourceModifyRequestIEs;
struct Ngap_PDUSessionResourceModifyResponseIEs;
struct Ngap_PDUSessionResourceNotifyIEs;
struct Ngap_PDUSessionResourceModifyIndicationIEs;
struct Ngap_PDUSessionResourceModifyConfirmIEs;
struct Ngap_InitialContextSetupRequestIEs;
struct Ngap_InitialContextSetupResponseIEs;
struct Ngap_InitialContextSetupFailureIEs;
struct Ngap_UEContextReleaseRequest_IEs;
struct Ngap_UEContextReleaseCommand_IEs;
struct Ngap_UEContextReleaseComplete_IEs;
struct Ngap_UEContextModificationRequestIEs;
struct Ngap_UEContextModificationResponseIEs;
struct Ngap_UEContextModificationFailureIEs;
struct Ngap_RRCInactiveTransitionReportIEs;
struct Ngap_HandoverRequiredIEs;
struct Ngap_HandoverCommandIEs;
struct Ngap_HandoverPreparationFailureIEs;
struct Ngap_HandoverRequestIEs;
struct Ngap_HandoverRequestAcknowledgeIEs;
struct Ngap_HandoverFailureIEs;
struct Ngap_HandoverNotifyIEs;
struct Ngap_PathSwitchRequestIEs;
struct Ngap_PathSwitchRequestAcknowledgeIEs;
struct Ngap_PathSwitchRequestFailureIEs;
struct Ngap_HandoverCancelIEs;
struct Ngap_HandoverCancelAcknowledgeIEs;
struct Ngap_UplinkRANStatusTransferIEs;
struct Ngap_DownlinkRANStatusTransferIEs;
struct Ngap_PagingIEs;
struct Ngap_InitialUEMessage_IEs;
struct Ngap_DownlinkNASTransport_IEs;
struct Ngap_UplinkNASTransport_IEs;
struct Ngap_NASNonDeliveryIndication_IEs;
struct Ngap_RerouteNASRequest_IEs;
struct Ngap_NGSetupRequestIEs;
struct Ngap_NGSetupResponseIEs;
struct Ngap_NGSetupFailureIEs;
struct Ngap_RANConfigurationUpdateIEs;
struct Ngap_RANConfigurationUpdateAcknowledgeIEs;
struct Ngap_RANConfigurationUpdateFailureIEs;
struct Ngap_AMFConfigurationUpdateIEs;
struct Ngap_AMFConfigurationUpdateAcknowledgeIEs;
struct Ngap_AMFConfigurationUpdateFailureIEs;
struct Ngap_AMFStatusIndicationIEs;
struct Ngap_NGResetIEs;
struct Ngap_NGResetAcknowledgeIEs;
struct Ngap_ErrorIndicationIEs;
struct Ngap_OverloadStartIEs;
struct Ngap_OverloadStopIEs;
struct Ngap_UplinkRANConfigurationTransferIEs;
struct Ngap_DownlinkRANConfigurationTransferIEs;
struct Ngap_WriteReplaceWarningRequestIEs;
struct Ngap_WriteReplaceWarningResponseIEs;
struct Ngap_PWSCancelRequestIEs;
struct Ngap_PWSCancelResponseIEs;
struct Ngap_PWSRestartIndicationIEs;
struct Ngap_PWSFailureIndicationIEs;
struct Ngap_DownlinkUEAssociatedNRPPaTransportIEs;
struct Ngap_UplinkUEAssociatedNRPPaTransportIEs;
struct Ngap_DownlinkNonUEAssociatedNRPPaTransportIEs;
struct Ngap_UplinkNonUEAssociatedNRPPaTransportIEs;
struct Ngap_TraceStartIEs;
struct Ngap_TraceFailureIndicationIEs;
struct Ngap_DeactivateTraceIEs;
struct Ngap_CellTrafficTraceIEs;
struct Ngap_LocationReportingControlIEs;
struct Ngap_LocationReportingFailureIndicationIEs;
struct Ngap_LocationReportIEs;
struct Ngap_UETNLABindingReleaseRequestIEs;
struct Ngap_UERadioCapabilityInfoIndicationIEs;
struct Ngap_UERadioCapabilityCheckRequestIEs;
struct Ngap_UERadioCapabilityCheckResponseIEs;
struct Ngap_SecondaryRATDataUsageReportIEs;

/* Ngap_ProtocolIE-Container */
typedef struct Ngap_ProtocolIE_Container_124P0 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P0_t;
typedef struct Ngap_ProtocolIE_Container_124P1 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceSetupRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P1_t;
typedef struct Ngap_ProtocolIE_Container_124P2 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P2_t;
typedef struct Ngap_ProtocolIE_Container_124P3 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P3_t;
typedef struct Ngap_ProtocolIE_Container_124P4 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceReleaseCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P4_t;
typedef struct Ngap_ProtocolIE_Container_124P5 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P5_t;
typedef struct Ngap_ProtocolIE_Container_124P6 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P6_t;
typedef struct Ngap_ProtocolIE_Container_124P7 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P7_t;
typedef struct Ngap_ProtocolIE_Container_124P8 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P8_t;
typedef struct Ngap_ProtocolIE_Container_124P9 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P9_t;
typedef struct Ngap_ProtocolIE_Container_124P10 {
	A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P10_t;
typedef struct Ngap_ProtocolIE_Container_124P11 {
	A_SEQUENCE_OF(struct Ngap_InitialContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P11_t;
typedef struct Ngap_ProtocolIE_Container_124P12 {
	A_SEQUENCE_OF(struct Ngap_InitialContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P12_t;
typedef struct Ngap_ProtocolIE_Container_124P13 {
	A_SEQUENCE_OF(struct Ngap_InitialContextSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P13_t;
typedef struct Ngap_ProtocolIE_Container_124P14 {
	A_SEQUENCE_OF(struct Ngap_UEContextReleaseRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P14_t;
typedef struct Ngap_ProtocolIE_Container_124P15 {
	A_SEQUENCE_OF(struct Ngap_UEContextReleaseCommand_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P15_t;
typedef struct Ngap_ProtocolIE_Container_124P16 {
	A_SEQUENCE_OF(struct Ngap_UEContextReleaseComplete_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P16_t;
typedef struct Ngap_ProtocolIE_Container_124P17 {
	A_SEQUENCE_OF(struct Ngap_UEContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P17_t;
typedef struct Ngap_ProtocolIE_Container_124P18 {
	A_SEQUENCE_OF(struct Ngap_UEContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P18_t;
typedef struct Ngap_ProtocolIE_Container_124P19 {
	A_SEQUENCE_OF(struct Ngap_UEContextModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P19_t;
typedef struct Ngap_ProtocolIE_Container_124P20 {
	A_SEQUENCE_OF(struct Ngap_RRCInactiveTransitionReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P20_t;
typedef struct Ngap_ProtocolIE_Container_124P21 {
	A_SEQUENCE_OF(struct Ngap_HandoverRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P21_t;
typedef struct Ngap_ProtocolIE_Container_124P22 {
	A_SEQUENCE_OF(struct Ngap_HandoverCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P22_t;
typedef struct Ngap_ProtocolIE_Container_124P23 {
	A_SEQUENCE_OF(struct Ngap_HandoverPreparationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P23_t;
typedef struct Ngap_ProtocolIE_Container_124P24 {
	A_SEQUENCE_OF(struct Ngap_HandoverRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P24_t;
typedef struct Ngap_ProtocolIE_Container_124P25 {
	A_SEQUENCE_OF(struct Ngap_HandoverRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P25_t;
typedef struct Ngap_ProtocolIE_Container_124P26 {
	A_SEQUENCE_OF(struct Ngap_HandoverFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P26_t;
typedef struct Ngap_ProtocolIE_Container_124P27 {
	A_SEQUENCE_OF(struct Ngap_HandoverNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P27_t;
typedef struct Ngap_ProtocolIE_Container_124P28 {
	A_SEQUENCE_OF(struct Ngap_PathSwitchRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P28_t;
typedef struct Ngap_ProtocolIE_Container_124P29 {
	A_SEQUENCE_OF(struct Ngap_PathSwitchRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P29_t;
typedef struct Ngap_ProtocolIE_Container_124P30 {
	A_SEQUENCE_OF(struct Ngap_PathSwitchRequestFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P30_t;
typedef struct Ngap_ProtocolIE_Container_124P31 {
	A_SEQUENCE_OF(struct Ngap_HandoverCancelIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P31_t;
typedef struct Ngap_ProtocolIE_Container_124P32 {
	A_SEQUENCE_OF(struct Ngap_HandoverCancelAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P32_t;
typedef struct Ngap_ProtocolIE_Container_124P33 {
	A_SEQUENCE_OF(struct Ngap_UplinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P33_t;
typedef struct Ngap_ProtocolIE_Container_124P34 {
	A_SEQUENCE_OF(struct Ngap_DownlinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P34_t;
typedef struct Ngap_ProtocolIE_Container_124P35 {
	A_SEQUENCE_OF(struct Ngap_PagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P35_t;
typedef struct Ngap_ProtocolIE_Container_124P36 {
	A_SEQUENCE_OF(struct Ngap_InitialUEMessage_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P36_t;
typedef struct Ngap_ProtocolIE_Container_124P37 {
	A_SEQUENCE_OF(struct Ngap_DownlinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P37_t;
typedef struct Ngap_ProtocolIE_Container_124P38 {
	A_SEQUENCE_OF(struct Ngap_UplinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P38_t;
typedef struct Ngap_ProtocolIE_Container_124P39 {
	A_SEQUENCE_OF(struct Ngap_NASNonDeliveryIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P39_t;
typedef struct Ngap_ProtocolIE_Container_124P40 {
	A_SEQUENCE_OF(struct Ngap_RerouteNASRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P40_t;
typedef struct Ngap_ProtocolIE_Container_124P41 {
	A_SEQUENCE_OF(struct Ngap_NGSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P41_t;
typedef struct Ngap_ProtocolIE_Container_124P42 {
	A_SEQUENCE_OF(struct Ngap_NGSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P42_t;
typedef struct Ngap_ProtocolIE_Container_124P43 {
	A_SEQUENCE_OF(struct Ngap_NGSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P43_t;
typedef struct Ngap_ProtocolIE_Container_124P44 {
	A_SEQUENCE_OF(struct Ngap_RANConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P44_t;
typedef struct Ngap_ProtocolIE_Container_124P45 {
	A_SEQUENCE_OF(struct Ngap_RANConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P45_t;
typedef struct Ngap_ProtocolIE_Container_124P46 {
	A_SEQUENCE_OF(struct Ngap_RANConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P46_t;
typedef struct Ngap_ProtocolIE_Container_124P47 {
	A_SEQUENCE_OF(struct Ngap_AMFConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P47_t;
typedef struct Ngap_ProtocolIE_Container_124P48 {
	A_SEQUENCE_OF(struct Ngap_AMFConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P48_t;
typedef struct Ngap_ProtocolIE_Container_124P49 {
	A_SEQUENCE_OF(struct Ngap_AMFConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P49_t;
typedef struct Ngap_ProtocolIE_Container_124P50 {
	A_SEQUENCE_OF(struct Ngap_AMFStatusIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P50_t;
typedef struct Ngap_ProtocolIE_Container_124P51 {
	A_SEQUENCE_OF(struct Ngap_NGResetIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P51_t;
typedef struct Ngap_ProtocolIE_Container_124P52 {
	A_SEQUENCE_OF(struct Ngap_NGResetAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P52_t;
typedef struct Ngap_ProtocolIE_Container_124P53 {
	A_SEQUENCE_OF(struct Ngap_ErrorIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P53_t;
typedef struct Ngap_ProtocolIE_Container_124P54 {
	A_SEQUENCE_OF(struct Ngap_OverloadStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P54_t;
typedef struct Ngap_ProtocolIE_Container_124P55 {
	A_SEQUENCE_OF(struct Ngap_OverloadStopIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P55_t;
typedef struct Ngap_ProtocolIE_Container_124P56 {
	A_SEQUENCE_OF(struct Ngap_UplinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P56_t;
typedef struct Ngap_ProtocolIE_Container_124P57 {
	A_SEQUENCE_OF(struct Ngap_DownlinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P57_t;
typedef struct Ngap_ProtocolIE_Container_124P58 {
	A_SEQUENCE_OF(struct Ngap_WriteReplaceWarningRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P58_t;
typedef struct Ngap_ProtocolIE_Container_124P59 {
	A_SEQUENCE_OF(struct Ngap_WriteReplaceWarningResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P59_t;
typedef struct Ngap_ProtocolIE_Container_124P60 {
	A_SEQUENCE_OF(struct Ngap_PWSCancelRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P60_t;
typedef struct Ngap_ProtocolIE_Container_124P61 {
	A_SEQUENCE_OF(struct Ngap_PWSCancelResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P61_t;
typedef struct Ngap_ProtocolIE_Container_124P62 {
	A_SEQUENCE_OF(struct Ngap_PWSRestartIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P62_t;
typedef struct Ngap_ProtocolIE_Container_124P63 {
	A_SEQUENCE_OF(struct Ngap_PWSFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P63_t;
typedef struct Ngap_ProtocolIE_Container_124P64 {
	A_SEQUENCE_OF(struct Ngap_DownlinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P64_t;
typedef struct Ngap_ProtocolIE_Container_124P65 {
	A_SEQUENCE_OF(struct Ngap_UplinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P65_t;
typedef struct Ngap_ProtocolIE_Container_124P66 {
	A_SEQUENCE_OF(struct Ngap_DownlinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P66_t;
typedef struct Ngap_ProtocolIE_Container_124P67 {
	A_SEQUENCE_OF(struct Ngap_UplinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P67_t;
typedef struct Ngap_ProtocolIE_Container_124P68 {
	A_SEQUENCE_OF(struct Ngap_TraceStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P68_t;
typedef struct Ngap_ProtocolIE_Container_124P69 {
	A_SEQUENCE_OF(struct Ngap_TraceFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P69_t;
typedef struct Ngap_ProtocolIE_Container_124P70 {
	A_SEQUENCE_OF(struct Ngap_DeactivateTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P70_t;
typedef struct Ngap_ProtocolIE_Container_124P71 {
	A_SEQUENCE_OF(struct Ngap_CellTrafficTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P71_t;
typedef struct Ngap_ProtocolIE_Container_124P72 {
	A_SEQUENCE_OF(struct Ngap_LocationReportingControlIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P72_t;
typedef struct Ngap_ProtocolIE_Container_124P73 {
	A_SEQUENCE_OF(struct Ngap_LocationReportingFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P73_t;
typedef struct Ngap_ProtocolIE_Container_124P74 {
	A_SEQUENCE_OF(struct Ngap_LocationReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P74_t;
typedef struct Ngap_ProtocolIE_Container_124P75 {
	A_SEQUENCE_OF(struct Ngap_UETNLABindingReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P75_t;
typedef struct Ngap_ProtocolIE_Container_124P76 {
	A_SEQUENCE_OF(struct Ngap_UERadioCapabilityInfoIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P76_t;
typedef struct Ngap_ProtocolIE_Container_124P77 {
	A_SEQUENCE_OF(struct Ngap_UERadioCapabilityCheckRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P77_t;
typedef struct Ngap_ProtocolIE_Container_124P78 {
	A_SEQUENCE_OF(struct Ngap_UERadioCapabilityCheckResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P78_t;
typedef struct Ngap_ProtocolIE_Container_124P79 {
	A_SEQUENCE_OF(struct Ngap_SecondaryRATDataUsageReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_124P79_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P0;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P0_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P0_1[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P1;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P1_specs_3;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P1_3[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P2;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P2_specs_5;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P2_5[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P3;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P3_specs_7;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P3_7[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P4;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P4_specs_9;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P4_9[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P5;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P5_specs_11;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P5_11[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P6;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P6_specs_13;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P6_13[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P7;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P7_specs_15;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P7_15[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P8;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P8_specs_17;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P8_17[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P9;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P9_specs_19;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P9_19[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P10;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P10_specs_21;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P10_21[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P11;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P11_specs_23;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P11_23[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P12;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P12_specs_25;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P12_25[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P13;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P13_specs_27;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P13_27[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P14;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P14_specs_29;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P14_29[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P15;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P15_specs_31;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P15_31[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P16;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P16_specs_33;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P16_33[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P17;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P17_specs_35;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P17_35[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P18;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P18_specs_37;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P18_37[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P19;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P19_specs_39;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P19_39[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P20;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P20_specs_41;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P20_41[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P21;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P21_specs_43;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P21_43[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P22;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P22_specs_45;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P22_45[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P23;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P23_specs_47;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P23_47[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P24;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P24_specs_49;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P24_49[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P25;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P25_specs_51;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P25_51[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P26;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P26_specs_53;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P26_53[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P27;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P27_specs_55;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P27_55[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P28;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P28_specs_57;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P28_57[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P29;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P29_specs_59;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P29_59[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P30;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P30_specs_61;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P30_61[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P31;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P31_specs_63;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P31_63[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P32;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P32_specs_65;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P32_65[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P33;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P33_specs_67;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P33_67[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P34;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P34_specs_69;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P34_69[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P35;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P35_specs_71;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P35_71[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P36;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P36_specs_73;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P36_73[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P37;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P37_specs_75;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P37_75[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P38;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P38_specs_77;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P38_77[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P39;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P39_specs_79;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P39_79[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P40;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P40_specs_81;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P40_81[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P41;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P41_specs_83;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P41_83[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P42;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P42_specs_85;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P42_85[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P43;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P43_specs_87;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P43_87[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P44;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P44_specs_89;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P44_89[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P45;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P45_specs_91;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P45_91[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P46;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P46_specs_93;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P46_93[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P47;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P47_specs_95;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P47_95[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P48;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P48_specs_97;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P48_97[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P49;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P49_specs_99;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P49_99[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P50;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P50_specs_101;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P50_101[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P51;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P51_specs_103;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P51_103[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P52;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P52_specs_105;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P52_105[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P53;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P53_specs_107;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P53_107[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P54;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P54_specs_109;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P54_109[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P55;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P55_specs_111;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P55_111[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P56;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P56_specs_113;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P56_113[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P57;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P57_specs_115;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P57_115[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P58;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P58_specs_117;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P58_117[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P59;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P59_specs_119;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P59_119[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P60;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P60_specs_121;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P60_121[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P61;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P61_specs_123;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P61_123[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P62;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P62_specs_125;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P62_125[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P63;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P63_specs_127;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P63_127[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P64;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P64_specs_129;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P64_129[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P65;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P65_specs_131;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P65_131[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P66;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P66_specs_133;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P66_133[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P67;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P67_specs_135;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P67_135[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P68;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P68_specs_137;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P68_137[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P69;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P69_specs_139;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P69_139[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P70;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P70_specs_141;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P70_141[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P71;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P71_specs_143;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P71_143[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P72;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P72_specs_145;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P72_145[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P73;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P73_specs_147;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P73_147[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P74;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P74_specs_149;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P74_149[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P75;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P75_specs_151;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P75_151[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P76;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P76_specs_153;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P76_153[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P77;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P77_specs_155;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P77_155[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P78;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P78_specs_157;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P78_157[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_124P79;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_124P79_specs_159;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_124P79_159[1];
extern asn_per_constraints_t asn_PER_type_Ngap_ProtocolIE_Container_124P79_constr_159;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_ProtocolIE_Container_H_ */
#include <asn_internal.h>
