/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_AMF_UE_NGAP_ID_H_
#define	_Ngap_AMF_UE_NGAP_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ngap_AMF-UE-NGAP-ID */
typedef INTEGER_t	 Ngap_AMF_UE_NGAP_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_AMF_UE_NGAP_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_AMF_UE_NGAP_ID;
asn_struct_free_f Ngap_AMF_UE_NGAP_ID_free;
asn_struct_print_f Ngap_AMF_UE_NGAP_ID_print;
asn_constr_check_f Ngap_AMF_UE_NGAP_ID_constraint;
ber_type_decoder_f Ngap_AMF_UE_NGAP_ID_decode_ber;
der_type_encoder_f Ngap_AMF_UE_NGAP_ID_encode_der;
xer_type_decoder_f Ngap_AMF_UE_NGAP_ID_decode_xer;
xer_type_encoder_f Ngap_AMF_UE_NGAP_ID_encode_xer;
oer_type_decoder_f Ngap_AMF_UE_NGAP_ID_decode_oer;
oer_type_encoder_f Ngap_AMF_UE_NGAP_ID_encode_oer;
per_type_decoder_f Ngap_AMF_UE_NGAP_ID_decode_uper;
per_type_encoder_f Ngap_AMF_UE_NGAP_ID_encode_uper;
per_type_decoder_f Ngap_AMF_UE_NGAP_ID_decode_aper;
per_type_encoder_f Ngap_AMF_UE_NGAP_ID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_AMF_UE_NGAP_ID_H_ */
#include <asn_internal.h>
