/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_CompletedCellsInEAI_EUTRA_H_
#define	_Ngap_CompletedCellsInEAI_EUTRA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_CompletedCellsInEAI_EUTRA_Item;

/* Ngap_CompletedCellsInEAI-EUTRA */
typedef struct Ngap_CompletedCellsInEAI_EUTRA {
	A_SEQUENCE_OF(struct Ngap_CompletedCellsInEAI_EUTRA_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_CompletedCellsInEAI_EUTRA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_CompletedCellsInEAI_EUTRA;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_CompletedCellsInEAI_EUTRA_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_CompletedCellsInEAI_EUTRA_1[1];
extern asn_per_constraints_t asn_PER_type_Ngap_CompletedCellsInEAI_EUTRA_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_CompletedCellsInEAI_EUTRA_H_ */
#include <asn_internal.h>
