/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_AMFPagingTarget_H_
#define	_Ngap_AMFPagingTarget_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_AMFPagingTarget_PR {
	Ngap_AMFPagingTarget_PR_NOTHING,	/* No components present */
	Ngap_AMFPagingTarget_PR_globalRANNodeID,
	Ngap_AMFPagingTarget_PR_tAI,
	Ngap_AMFPagingTarget_PR_choice_Extensions
} Ngap_AMFPagingTarget_PR;

/* Forward declarations */
struct Ngap_GlobalRANNodeID;
struct Ngap_TAI;
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_AMFPagingTarget */
typedef struct Ngap_AMFPagingTarget {
	Ngap_AMFPagingTarget_PR present;
	union Ngap_AMFPagingTarget_u {
		struct Ngap_GlobalRANNodeID	*globalRANNodeID;
		struct Ngap_TAI	*tAI;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_AMFPagingTarget_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_AMFPagingTarget;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_AMFPagingTarget_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_AMFPagingTarget_1[3];
extern asn_per_constraints_t asn_PER_type_Ngap_AMFPagingTarget_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_AMFPagingTarget_H_ */
#include <asn_internal.h>
