/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#include "Ngap_CellIDListForRestart.h"

#include "Ngap_EUTRA-CGIList.h"
#include "Ngap_NR-CGIList.h"
#include "Ngap_ProtocolIE-SingleContainer.h"
static asn_oer_constraints_t asn_OER_type_Ngap_CellIDListForRestart_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Ngap_CellIDListForRestart_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Ngap_CellIDListForRestart_1[] = {
	{ ATF_POINTER, 0, offsetof(struct Ngap_CellIDListForRestart, choice.eUTRA_CGIListforRestart),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_EUTRA_CGIList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eUTRA-CGIListforRestart"
		},
	{ ATF_POINTER, 0, offsetof(struct Ngap_CellIDListForRestart, choice.nR_CGIListforRestart),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_NR_CGIList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nR-CGIListforRestart"
		},
	{ ATF_POINTER, 0, offsetof(struct Ngap_CellIDListForRestart, choice.choice_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_ProtocolIE_SingleContainer_127P4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-Extensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Ngap_CellIDListForRestart_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eUTRA-CGIListforRestart */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* nR-CGIListforRestart */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* choice-Extensions */
};
asn_CHOICE_specifics_t asn_SPC_Ngap_CellIDListForRestart_specs_1 = {
	sizeof(struct Ngap_CellIDListForRestart),
	offsetof(struct Ngap_CellIDListForRestart, _asn_ctx),
	offsetof(struct Ngap_CellIDListForRestart, present),
	sizeof(((struct Ngap_CellIDListForRestart *)0)->present),
	asn_MAP_Ngap_CellIDListForRestart_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Ngap_CellIDListForRestart = {
	"CellIDListForRestart",
	"CellIDListForRestart",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Ngap_CellIDListForRestart_constr_1, &asn_PER_type_Ngap_CellIDListForRestart_constr_1, CHOICE_constraint },
	asn_MBR_Ngap_CellIDListForRestart_1,
	3,	/* Elements count */
	&asn_SPC_Ngap_CellIDListForRestart_specs_1	/* Additional specs */
};

