/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#include "Ngap_BroadcastCompletedAreaList.h"

#include "Ngap_CellIDBroadcastEUTRA.h"
#include "Ngap_TAIBroadcastEUTRA.h"
#include "Ngap_EmergencyAreaIDBroadcastEUTRA.h"
#include "Ngap_CellIDBroadcastNR.h"
#include "Ngap_TAIBroadcastNR.h"
#include "Ngap_EmergencyAreaIDBroadcastNR.h"
#include "Ngap_ProtocolIE-SingleContainer.h"
static asn_oer_constraints_t asn_OER_type_Ngap_BroadcastCompletedAreaList_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Ngap_BroadcastCompletedAreaList_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Ngap_BroadcastCompletedAreaList_1[] = {
	{ ATF_POINTER, 0, offsetof(struct Ngap_BroadcastCompletedAreaList, choice.cellIDBroadcastEUTRA),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_CellIDBroadcastEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellIDBroadcastEUTRA"
		},
	{ ATF_POINTER, 0, offsetof(struct Ngap_BroadcastCompletedAreaList, choice.tAIBroadcastEUTRA),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_TAIBroadcastEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tAIBroadcastEUTRA"
		},
	{ ATF_POINTER, 0, offsetof(struct Ngap_BroadcastCompletedAreaList, choice.emergencyAreaIDBroadcastEUTRA),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_EmergencyAreaIDBroadcastEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"emergencyAreaIDBroadcastEUTRA"
		},
	{ ATF_POINTER, 0, offsetof(struct Ngap_BroadcastCompletedAreaList, choice.cellIDBroadcastNR),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_CellIDBroadcastNR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellIDBroadcastNR"
		},
	{ ATF_POINTER, 0, offsetof(struct Ngap_BroadcastCompletedAreaList, choice.tAIBroadcastNR),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_TAIBroadcastNR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tAIBroadcastNR"
		},
	{ ATF_POINTER, 0, offsetof(struct Ngap_BroadcastCompletedAreaList, choice.emergencyAreaIDBroadcastNR),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_EmergencyAreaIDBroadcastNR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"emergencyAreaIDBroadcastNR"
		},
	{ ATF_POINTER, 0, offsetof(struct Ngap_BroadcastCompletedAreaList, choice.choice_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ngap_ProtocolIE_SingleContainer_127P2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-Extensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Ngap_BroadcastCompletedAreaList_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellIDBroadcastEUTRA */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tAIBroadcastEUTRA */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* emergencyAreaIDBroadcastEUTRA */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* cellIDBroadcastNR */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* tAIBroadcastNR */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* emergencyAreaIDBroadcastNR */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* choice-Extensions */
};
asn_CHOICE_specifics_t asn_SPC_Ngap_BroadcastCompletedAreaList_specs_1 = {
	sizeof(struct Ngap_BroadcastCompletedAreaList),
	offsetof(struct Ngap_BroadcastCompletedAreaList, _asn_ctx),
	offsetof(struct Ngap_BroadcastCompletedAreaList, present),
	sizeof(((struct Ngap_BroadcastCompletedAreaList *)0)->present),
	asn_MAP_Ngap_BroadcastCompletedAreaList_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Ngap_BroadcastCompletedAreaList = {
	"BroadcastCompletedAreaList",
	"BroadcastCompletedAreaList",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Ngap_BroadcastCompletedAreaList_constr_1, &asn_PER_type_Ngap_BroadcastCompletedAreaList_constr_1, CHOICE_constraint },
	asn_MBR_Ngap_BroadcastCompletedAreaList_1,
	7,	/* Elements count */
	&asn_SPC_Ngap_BroadcastCompletedAreaList_specs_1	/* Additional specs */
};

