/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-CommonDataTypes"
 * 	found in "asn.1/Common Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_TriggeringMessage_H_
#define	_Ngap_TriggeringMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_TriggeringMessage {
	Ngap_TriggeringMessage_initiating_message	= 0,
	Ngap_TriggeringMessage_successful_outcome	= 1,
	Ngap_TriggeringMessage_unsuccessfull_outcome	= 2
} e_Ngap_TriggeringMessage;

/* Ngap_TriggeringMessage */
typedef long	 Ngap_TriggeringMessage_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_TriggeringMessage_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_TriggeringMessage;
extern const asn_INTEGER_specifics_t asn_SPC_TriggeringMessage_specs_1;
asn_struct_free_f TriggeringMessage_free;
asn_struct_print_f TriggeringMessage_print;
asn_constr_check_f TriggeringMessage_constraint;
ber_type_decoder_f TriggeringMessage_decode_ber;
der_type_encoder_f TriggeringMessage_encode_der;
xer_type_decoder_f TriggeringMessage_decode_xer;
xer_type_encoder_f TriggeringMessage_encode_xer;
oer_type_decoder_f TriggeringMessage_decode_oer;
oer_type_encoder_f TriggeringMessage_encode_oer;
per_type_decoder_f TriggeringMessage_decode_uper;
per_type_encoder_f TriggeringMessage_encode_uper;
per_type_decoder_f TriggeringMessage_decode_aper;
per_type_encoder_f TriggeringMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_TriggeringMessage_H_ */
#include <asn_internal.h>
