/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_QosFlowSetupResponseListSURes_H_
#define	_Ngap_QosFlowSetupResponseListSURes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_QosFlowSetupResponseItemSURes;

/* Ngap_QosFlowSetupResponseListSURes */
typedef struct Ngap_QosFlowSetupResponseListSURes {
	A_SEQUENCE_OF(struct Ngap_QosFlowSetupResponseItemSURes) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_QosFlowSetupResponseListSURes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_QosFlowSetupResponseListSURes;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_QosFlowSetupResponseListSURes_H_ */
#include <asn_internal.h>
