/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_CellIDListForRestart_H_
#define	_Ngap_CellIDListForRestart_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_CellIDListForRestart_PR {
	Ngap_CellIDListForRestart_PR_NOTHING,	/* No components present */
	Ngap_CellIDListForRestart_PR_eUTRA_CGIListforRestart,
	Ngap_CellIDListForRestart_PR_nR_CGIListforRestart,
	Ngap_CellIDListForRestart_PR_choice_Extensions
} Ngap_CellIDListForRestart_PR;

/* Forward declarations */
struct Ngap_EUTRA_CGIList;
struct Ngap_NR_CGIList;
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_CellIDListForRestart */
typedef struct Ngap_CellIDListForRestart {
	Ngap_CellIDListForRestart_PR present;
	union Ngap_CellIDListForRestart_u {
		struct Ngap_EUTRA_CGIList	*eUTRA_CGIListforRestart;
		struct Ngap_NR_CGIList	*nR_CGIListforRestart;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_CellIDListForRestart_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_CellIDListForRestart;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_CellIDListForRestart_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_CellIDListForRestart_1[3];
extern asn_per_constraints_t asn_PER_type_Ngap_CellIDListForRestart_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_CellIDListForRestart_H_ */
#include <asn_internal.h>
