/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "asn.1/Information Element Definitions.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -findirect-choice -gen-PER -D src`
 */

#ifndef	_Ngap_BroadcastCancelledAreaList_H_
#define	_Ngap_BroadcastCancelledAreaList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_BroadcastCancelledAreaList_PR {
	Ngap_BroadcastCancelledAreaList_PR_NOTHING,	/* No components present */
	Ngap_BroadcastCancelledAreaList_PR_cellIDCancelledEUTRA,
	Ngap_BroadcastCancelledAreaList_PR_tAICancelledEUTRA,
	Ngap_BroadcastCancelledAreaList_PR_emergencyAreaIDCancelledEUTRA,
	Ngap_BroadcastCancelledAreaList_PR_cellIDCancelledNR,
	Ngap_BroadcastCancelledAreaList_PR_tAICancelledNR,
	Ngap_BroadcastCancelledAreaList_PR_emergencyAreaIDCancelledNR,
	Ngap_BroadcastCancelledAreaList_PR_choice_Extensions
} Ngap_BroadcastCancelledAreaList_PR;

/* Forward declarations */
struct Ngap_CellIDCancelledEUTRA;
struct Ngap_TAICancelledEUTRA;
struct Ngap_EmergencyAreaIDCancelledEUTRA;
struct Ngap_CellIDCancelledNR;
struct Ngap_TAICancelledNR;
struct Ngap_EmergencyAreaIDCancelledNR;
struct Ngap_ProtocolIE_SingleContainer;

/* Ngap_BroadcastCancelledAreaList */
typedef struct Ngap_BroadcastCancelledAreaList {
	Ngap_BroadcastCancelledAreaList_PR present;
	union Ngap_BroadcastCancelledAreaList_u {
		struct Ngap_CellIDCancelledEUTRA	*cellIDCancelledEUTRA;
		struct Ngap_TAICancelledEUTRA	*tAICancelledEUTRA;
		struct Ngap_EmergencyAreaIDCancelledEUTRA	*emergencyAreaIDCancelledEUTRA;
		struct Ngap_CellIDCancelledNR	*cellIDCancelledNR;
		struct Ngap_TAICancelledNR	*tAICancelledNR;
		struct Ngap_EmergencyAreaIDCancelledNR	*emergencyAreaIDCancelledNR;
		struct Ngap_ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_BroadcastCancelledAreaList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_BroadcastCancelledAreaList;
extern asn_CHOICE_specifics_t asn_SPC_Ngap_BroadcastCancelledAreaList_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_BroadcastCancelledAreaList_1[7];
extern asn_per_constraints_t asn_PER_type_Ngap_BroadcastCancelledAreaList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_BroadcastCancelledAreaList_H_ */
#include <asn_internal.h>
